# Generated by Django 4.1.1 on 2023-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('faddress', models.TextField()),
                ('laddress', models.TextField()),
            ],
        ),
    ]
