# Generated by Django 4.1.1 on 2023-03-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_registerdb_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
