# Generated by Django 4.1.1 on 2023-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_registerdb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loggdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='status',
        ),
    ]
